# For more information: https://laravel.com/docs/sail
services:
    mailhog:
        container_name: bookmark-mailhog
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - bookmark
networks:
    bookmark:
        name: 'bookmark'
        driver: bridge
