[tool.black]
line-length = 160
exclude = 'tests/'

[tool.pylint.MASTER]
load-plugins = "pylint_django"

[tool.pylint.FORMAT]
max-line-length = 160

[tool.pylint.DESIGN]
max-args = 10
max-locals = 25
max-branches = 20
max-statements = 60

[tool.pylint.DJANGO]
django-settings-module = "flexible_web_checker.settings"

[tool.pylint.messages_control]
disable = [
    "W0718",
]
